### ISSUE TITLE
MyVD Startup Error

### ISSUE THREAD

**Issue by KishoreKumarSE** [TremoloSecurity/MyVirtualDirectory#116]
Hi,

We configured MyVD software for our Domains and when we start the myvd in windows server we are getting the below error.
Can you assist.

[2021-11-22 09:16:59,552][main] INFO  Server - MyVirtualDirectory Version : 1.0.9
[2021-11-22 09:16:59,557][main] INFO  Server - Starting MyVirtualDirectory server...
[2021-11-22 09:16:59,561][main] INFO  Server - ApacheDS System Directory Path : 'D:\Oracle\MYVDServer-1.0.9\conf\apacheds-data'
[2021-11-22 09:16:59,619][main] ERROR Server - Error starting server : java.lang.NullPointerException
java.lang.NullPointerException: null
	at java.util.StringTokenizer.<init>(StringTokenizer.java:199) ~[?:1.8.0_291]
	at java.util.StringTokenizer.<init>(StringTokenizer.java:221) ~[?:1.8.0_291]
	at net.sourceforge.myvd.server.ServerCore.buildNamespaces(ServerCore.java:119) ~[myvd-server-1.0.9.jar:?]
	at net.sourceforge.myvd.server.ServerCore.startService(ServerCore.java:150) ~[myvd-server-1.0.9.jar:?]
	at net.sourceforge.myvd.server.Server.startServer(Server.java:192) ~[myvd-server-1.0.9.jar:?]
	at net.sourceforge.myvd.server.Server.main(Server.java:534) [myvd-server-1.0.9.jar:?]

Regards,
Kishore

**Comment by clayrisser** [comment]
I'm facing the same issue. @mlbiam what was the solution?

**Comment by clayrisser** [comment]
Oh, in my case I was using `server.namespaces` instead of `server.nameSpaces`.
