### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by rkumar2236** [TremoloSecurity/MyVirtualDirectory#36]
**I am trying to compile this project but getting following error**

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Running net.sourceforge.myvd.test.ldap.TestEmbededGroups
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 10.921 sec <<< FAILURE! - in net.sourceforge.myvd.test.ldap.TestEmbededGroups
net.sourceforge.myvd.test.ldap.TestEmbededGroups  Time elapsed: 10.921 sec  <<< ERROR!
java.io.FileNotFoundException: null/test/EmbeddedGroups/slapd.conf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.createTestConf(StartOpenLDAP.java:237)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.startServer(StartOpenLDAP.java:193)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.startServer(StartOpenLDAP.java:155)
	at net.sourceforge.myvd.test.ldap.TestEmbededGroups.setUp(TestEmbededGroups.java:49)

net.sourceforge.myvd.test.ldap.TestEmbededGroups  Time elapsed: 10.921 sec  <<< ERROR!
java.lang.NullPointerException: null
	at net.sourceforge.myvd.test.ldap.TestEmbededGroups.tearDown(TestEmbededGroups.java:264)

**Comment by mlbiam** [comment]
@rkumar2236 if you just want to compile, but don't want to run the unit tests use `mvn package -DskipTests`
