### ISSUE TITLE
Test Cases Failing

### ISSUE THREAD

**Issue by sakthig** [TremoloSecurity/MyVirtualDirectory#49]
Hi when i try to do mvn package the tests are failing and i am unable to proceed.

`
Running net.sourceforge.myvd.test.ref.TestRefPlugin
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.331 sec <<< FAILURE! - in net.sourceforge.myvd.test.ref.TestRefPlugin
net.sourceforge.myvd.test.ref.TestRefPlugin  Time elapsed: 0.33 sec  <<< ERROR!
java.io.FileNotFoundException: null/test/Base/slapd.conf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.createTestConf(StartOpenLDAP.java:237)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.startServer(StartOpenLDAP.java:193)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.startServer(StartOpenLDAP.java:155)
	at net.sourceforge.myvd.test.ref.TestRefPlugin.setUp(TestRefPlugin.java:102)

net.sourceforge.myvd.test.ref.TestRefPlugin  Time elapsed: 0.331 sec  <<< ERROR!
java.lang.NullPointerException: null
	at net.sourceforge.myvd.test.ref.TestRefPlugin.tearDown(TestRefPlugin.java:701)

Running net.sourceforge.myvd.test.join.TestJoin
Tests run: 20, Failures: 0, Errors: 20, Skipped: 0, Time elapsed: 4.614 sec <<< FAILURE! - in net.sourceforge.myvd.test.join.TestJoin
testModJoined(net.sourceforge.myvd.test.join.TestJoin)  Time elapsed: 1.52 sec  <<< ERROR!
java.io.FileNotFoundException: null/test/TestJoin/ldap/slapd.conf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.createTestConf(StartOpenLDAP.java:237)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.startServer(StartOpenLDAP.java:193)
	at net.sourceforge.myvd.test.util.StartOpenLDAP.startServer(StartOpenLDAP.java:155)
	at net.sourceforge.myvd.test.join.TestJoin.setUp(TestJoin.java:119)
`

**Comment by mlbiam** [comment]
take a look at https://github.com/TremoloSecurity/MyVirtualDirectory

**Comment by sakthig** [comment]
Whom should i reach out for any other help ?

**Comment by mlbiam** [comment]
please continue to open issues on github
