### ISSUE TITLE
Issue on enabling SSL connection.

### ISSUE THREAD

**Issue by dineshbade** [TremoloSecurity/MyVirtualDirectory#55]
We are having issue on connection myvitualDirectory while enabling SSL through apache client 
This is stacktrace: -
`
[INFO ] 2019-03-19 16:43:34.090 [main] LdapServer - Successful bind of an LDAP Service (636) is completed.
[INFO ] 2019-03-19 16:43:34.090 [main] LdapServer - Ldap service started.
[INFO ] 2019-03-19 16:43:34.091 [main] Server - Server started
[DEBUG] 2019-03-19 16:43:46.869 [NioProcessor-2] SslFilter - Adding the SSL Filter sslFilter to the chain
[DEBUG] 2019-03-19 16:43:46.873 [NioProcessor-2] SslHandler - Session Server[1](no sslEngine) Initializing the SSL Handler
[DEBUG] 2019-03-19 16:43:46.908 [NioProcessor-2] SslHandler - Session Server[1](no sslEngine) SSL Handler Initialization done.
[DEBUG] 2019-03-19 16:43:46.908 [NioProcessor-2] SslFilter - Session Server[1](ssl...) : Starting the first handshake
[DEBUG] 2019-03-19 16:43:47.261 [NioProcessor-2] SslHandler - Session Server[1](ssl...) processing the NEED_UNWRAP state
[WARN ] 2019-03-19 16:43:47.328 [NioProcessor-2] LdapProtocolHandler - Unexpected exception forcing session to close: sending disconnect notice to client.
javax.net.ssl.SSLException: Improper close state: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 7 sequenceNumber = 0
	at org.apache.mina.filter.ssl.SslHandler.closeOutbound(SslHandler.java:494) ~[apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.ssl.SslFilter.initiateClosure(SslFilter.java:705) ~[apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.ssl.SslFilter.filterClose(SslFilter.java:663) ~[apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:644) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1600(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterClose(DefaultIoFilterChain.java:958) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.IoFilterAdapter.filterClose(IoFilterAdapter.java:130) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:644) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1600(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterClose(DefaultIoFilterChain.java:958) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.executor.ExecutorFilter.filterClose(ExecutorFilter.java:626) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:644) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1600(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterClose(DefaultIoFilterChain.java:958) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.filterClose(DefaultIoFilterChain.java:882) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:644) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireFilterClose(DefaultIoFilterChain.java:637) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.session.AbstractIoSession.close(AbstractIoSession.java:318) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.session.AbstractIoSession.close(AbstractIoSession.java:297) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.service.IoHandlerAdapter.inputClosed(IoHandlerAdapter.java:69) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.inputClosed(DefaultIoFilterChain.java:834) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextInputClosed(DefaultIoFilterChain.java:611) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.inputClosed(DefaultIoFilterChain.java:938) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.IoFilterAdapter.inputClosed(IoFilterAdapter.java:137) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextInputClosed(DefaultIoFilterChain.java:611) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.inputClosed(DefaultIoFilterChain.java:938) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.IoFilterAdapter.inputClosed(IoFilterAdapter.java:137) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextInputClosed(DefaultIoFilterChain.java:611) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.inputClosed(DefaultIoFilterChain.java:938) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.IoFilterAdapter.inputClosed(IoFilterAdapter.java:137) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextInputClosed(DefaultIoFilterChain.java:611) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.inputClosed(DefaultIoFilterChain.java:938) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.IoFilterAdapter.inputClosed(IoFilterAdapter.java:137) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextInputClosed(DefaultIoFilterChain.java:611) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireInputClosed(DefaultIoFilterChain.java:604) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:729) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:668) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:657) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1121) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[DEBUG] 2019-03-19 16:43:47.340 [NioProcessor-2] LdapProtocolHandler - Cleaning the LdapSession : No Ldap session ... session
[DEBUG] 2019-03-19 16:43:47.341 [NioProcessor-2] SslHandler - Unexpected exception from SSLEngine.closeInbound().
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at sun.security.ssl.Alert.createSSLException(Alert.java:129) ~[?:?]
	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:264) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:255) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:724) ~[?:?]
	at org.apache.mina.filter.ssl.SslHandler.destroy(SslHandler.java:208) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.ssl.SslFilter.sessionClosed(SslFilter.java:459) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:504) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$900(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionClosed(DefaultIoFilterChain.java:923) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:88) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:504) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireSessionClosed(DefaultIoFilterChain.java:497) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.service.IoServiceListenerSupport.fireSessionDestroyed(IoServiceListenerSupport.java:244) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.removeNow(AbstractPollingIoProcessor.java:604) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.removeSessions(AbstractPollingIoProcessor.java:564) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$800(AbstractPollingIoProcessor.java:67) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1129) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[DEBUG] 2019-03-19 16:43:47.345 [NioProcessor-2] LdapProtocolHandler - Null LdapSession given to cleanUpSession.
`

**Comment by mlbiam** [comment]
it looks like the client is closing the connection.  What is the client?

**Comment by dineshbade** [comment]
I have tried with both apache directory studio and ldp browser . None of them could able to make ssl connection.

**Comment by dineshbade** [comment]
Now i am getting no cipher suites in commons:-
Following is stacktrace
`
[WARN ] 2019-03-21 08:25:32.097 [NioProcessor-2] LdapProtocolHandler - Unexpected exception forcing session to close: sending disconnect notice to client.
javax.net.ssl.SSLHandshakeException: SSL handshake failed.
	at org.apache.mina.filter.ssl.SslFilter.messageReceived(SslFilter.java:507) ~[apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:714) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:668) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:657) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1121) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: no cipher suites in common
	at sun.security.ssl.Alert.createSSLException(Alert.java:128) ~[?:?]
	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:264) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:255) ~[?:?]
	at sun.security.ssl.ServerHello$T12ServerHelloProducer.chooseCipherSuite(ServerHello.java:461) ~[?:?]
	at sun.security.ssl.ServerHello$T12ServerHelloProducer.produce(ServerHello.java:294) ~[?:?]
	at sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436) ~[?:?]
	at sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1101) ~[?:?]
	at sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:851) ~[?:?]
	at sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:810) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1065) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1052) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:999) ~[?:?]
	at org.apache.mina.filter.ssl.SslHandler.doTasks(SslHandler.java:779) ~[apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.ssl.SslHandler.handshake(SslHandler.java:561) ~[apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.ssl.SslHandler.messageReceived(SslHandler.java:355) ~[apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.ssl.SslFilter.messageReceived(SslFilter.java:488) ~[apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	... 15 more`

**Comment by mlbiam** [comment]
Can you try using the openssl command to get the certificate from myvd?

`openssl s_client -connect 'host:10636`

This will at least tell you if MyVD is configured to listen on TLS and give you the certificate and handshake information being presented.
