### ISSUE TITLE
PatternSyntaxException

### ISSUE THREAD

**Issue by KarlKnapp** [TremoloSecurity/MyVirtualDirectory#67]
`[2019-07-26 10:48:34,860][pool-4-thread-6] ERROR JdbcEntrySet - Error processing search
java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 4
(?i:+49.*1.*2.*3.*4.*5.*6.*7.*8.*9)
    ^
                at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.group0(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.<init>(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_211]
                at java.util.regex.Pattern.matches(Unknown Source) ~[?:1.8.0_211]
                at java.lang.String.matches(Unknown Source) ~[?:1.8.0_211]
                at net.sourceforge.myvd.types.FilterNode.checkEntry(FilterNode.java:232) ~[myvd-server-1.0.6.jar:?]`

**Comment by mlbiam** [comment]
what input generates this exception?

**Comment by KarlKnapp** [comment]
a phone number with leading + sign
