### ISSUE TITLE
MyVD Connection Error

### ISSUE THREAD

**Issue by ShivankSiemens** [TremoloSecurity/MyVirtualDirectory#7]
[myvd.log.txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/570826/myvd.log.txt)

Hi Marc,

As discussed over email, I have attached the log file for your analysis.
It says the problem is with the username. But if I change the domain to the old one, It works fine. Only when I am connecting to the server where myVD proxy is running using the config file we have defined . we get the error.

Thanks,
Shivank

**Comment by mlbiam** [comment]
Looking at the logs I see

> 2016-11-03 16:07:20,384][NioProcessor-2] ERROR StoreName - Incorrect DN given : bw12primaz (0x62 0x77 0x31 0x32 0x70 0x72 0x69 0x6D 0x61 0x7A ) is invalid : ERR_04202 A value is missing on some RDN

This means that a value is missing from the RDN of either your search base or your bind DN.  Can you provide both?

**Comment by ShivankSiemens** [comment]
Hi,

I have uploaded the configuration file being used.
The Server name and Passwords have been written like <MASKED_ CAPS>.

I have tried putting username in below two formats in our application configuration.
1. Username: bw12primaz
2. Username: CN=bw12primaz,OU=Users,OU=AccSvc,OU=OPFW,OU=Admin,DC=ww009,DC=siemens,DC=net

case1 - error as in logs
case2 - bind failed error 

But if I put the actual ldap server and not the myVD server, I can connect in both cases.

[myvd.conf.txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/574758/myvd.conf.txt)

**Comment by ShivankSiemens** [comment]
Hi,
I have uploaded the configuration file being used.
The Server name and Passwords have been written like <MASKED_CAPS>
I have tried putting username in below two formats in our application configuration.
1. Username: bw12primaz
2. Username: CN=bw12primaz,OU=Users,OU=AccSvc,OU=OPFW,OU=Admin,DC=ww009,DC=siemens,DC=net
case1 - error as in logs
case2 - bind failed error
But if I put the actual ldap server and not the myVD server, I can connect in both cases.

Thanks,
Shivank

**Comment by mlbiam** [comment]
First question, once MyVD is running can you browse the directories using either a command line too or GUI?  That will ensure that you are at least properly configured.

**Comment by mlbiam** [comment]
Replace your server.globalChain= with

```
server.globalChain=dt
server.globalChain.dt.className=net.sourceforge.myvd.inserts.DumpTransaction
server.globalChain.dt.config.logLevel=info
server.globalChain.dt.config.label=global
```

**Comment by ShivankSiemens** [comment]
Hi Marc,

Thanks a lot for your help today.

PFA the log file as requested.

Tried login with the user account: z003n90u

New domain is: ad001
Old domain is: Siemens.net (ww002)


Regards,
Shivank
+49 163 9091798

**Comment by ShivankSiemens** [comment]
[myvd.log.txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/592514/myvd.log.txt)

**Comment by mlbiam** [comment]
@ShivankSiemens The logs aren't telling me what I need to know.  How do you know that z003n90u is disabled in the old AD?  Is there an attribute or are you talking the standard windows disabled flag in userAccountControl?

**Comment by ShivankSiemens** [comment]
Hi Marc,

Yes the user account control field is used for deactivation purpose.

The used field in active directory is:
UserAccountControl = 512 (enabled)
UserAccountControl = 514 (disabled)

Let me know if it helps.

I have tried with a new configuration of Primavera as well. It seems, we have to determine the account status and return the active one to Primavera for login.


Thanks,
Shivank

**Comment by mlbiam** [comment]
@ShivankSiemens I created a new feature request #9 for this.  I should have something working today I can get you.  In the mean time, I noticed you were running jdk 1.7.  MyVD 1.0.0 (what we moved to GitHub) requires Java 8 so I would get that installed.

**Comment by mlbiam** [comment]
@ShivankSiemens I have a working prototype.  

1.  Download https://www.tremolosecurity.com/dwn/tremolosecurity-downloads/myvd/1.0.0/myvd-server-1.0.0.zip
2.  Install Oracle's JDK 1.8
3.  Copy the config file from your old MyVD install to the new one
4.  Update myvd.bat to point to your keystore
5.  add the below config:

inside of your config, look for 

```
server.ww002.chain=uuid2text,dnmapper,objmap,membertrans,ldap
```

and change it to
```
server.ww002.chain=uuid2text,dnmapper,objmap,membertrans,filterDisabled,addEnabledFlag,ldap
```

then add the following to the ww002 block before the ldap insert configuration:
```
server.ww002.filterDisabled.className=net.sourceforge.myvd.inserts.mapping.EntryFilter
server.ww002.filterDisabled.config.objectClass=user
server.ww002.filterDisabled.config.filter=(!(userEnabled=false))
server.ww002.addEnabledFlag.className=net.sourceforge.myvd.inserts.mapping.AddActiveDirectoryEnabledFlag
server.ww002.addEnabledFlag.config.nameOfAttributeToCreate=userEnabled
```

this should block all disabled users from coming back as part of a search request

**Comment by ShivankSiemens** [comment]
Hi Marc,

I followed all the steps given below.
The new myvd.bat file is not even starting.

I have attached the logs for yur reference.
It seems to be related to the java class for uuid2text insert.

Can you pls. advise further.

Thanks,
Shivank

**Comment by ShivankSiemens** [comment]
@mlbiam

**Comment by mlbiam** [comment]
@ShivankSiemens download https://www.tremolosecurity.com/nexus/service/local/repositories/releases/content/com/tremolosecurity/unison/unison-myvd/1.0.8/unison-myvd-1.0.8.jar into your libs directory.  That should take care of the class issues

**Comment by ShivankSiemens** [comment]
@mlbiam Hi Marc,
I have updated the lib directory and Server started.
But now, no login is possible (old as well as new domain - active account)

I am attaching the logs again.
It seems the user mentioned in config file is able to bind but not search other users in LDAP.

Pls. advise.
[myvd.log.txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/600113/myvd.log.txt)

Thanks,
Shivank

**Comment by mlbiam** [comment]
@ShivankSiemens i see the issue.  has to do with requesting attributes.  Let me fix and get a new build ready

**Comment by mlbiam** [comment]
@ShivankSiemens need to replace myvd's main jar file:

1.  stop MyVD
2.  delete libs/myvd-server-1.0.0.jar
3.  download https://www.tremolosecurity.com/nexus/service/local/repositories/releases/content/net/sourceforge/myvd/myvd-server/1.0.0/myvd-server-1.0.0.jar and place it in the libs directory
4.  start myvd

**Comment by ShivankSiemens** [comment]
@mlbiam Hi Marc,

Tried this as well.

I am attaching another log file. But now it seems, logs are not even generating after re-starting the server.

I stopped and started server many time to get new log file.
Even renamed the old one. But new log file was not generated.

The entry you see at 15:48 - server started was after the main jar file was replaced and server started again.

Kindly help.



[myvd.log.txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/600199/myvd.log.txt)
Thanks,
Shivank

**Comment by mlbiam** [comment]
@ShivankSiemens can you post your latest config?  Looking at the logs I see:

```
[2016-11-18 15:49:28,921][pool-4-thread-2] INFO  DumpTransaction - [global] Error Running Search
java.lang.IllegalArgumentException: CN=w99sb700 ,OU=UsersFunctional,OU=_Central,OU=AccSvc,OU=RA005,_DC=ad001,DC=siemens,DC=net
	at com.novell.ldap.util.DN.<init>(DN.java:150) ~[jldap-1.0.0.jar:?]
	at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.getConnection(LDAPInterceptor.java:200) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.getConnection(LDAPInterceptor.java:189) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.inserts.ldap.LDAPInterceptor.search(LDAPInterceptor.java:434) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.inserts.mapping.AttributeMapper.search(AttributeMapper.java:164) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.inserts.mapping.AttributeValueMapper.search(AttributeValueMapper.java:190) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.inserts.mapping.DNAttributeMapper.search(DNAttributeMapper.java:214) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.0.jar:?]
	at com.tremolosecurity.proxy.myvd.inserts.util.UUIDtoText.search(UUIDtoText.java:147) ~[unison-myvd-1.0.8.jar:?]
	at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.router.Router.search(Router.java:364) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:60) ~[myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.inserts.DumpTransaction.search(DumpTransaction.java:279) [myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.chain.SearchInterceptorChain.nextSearch(SearchInterceptorChain.java:57) [myvd-server-1.0.0.jar:?]
	at net.sourceforge.myvd.server.apacheds.MyVDInterceptor.search(MyVDInterceptor.java:781) [myvd-server-1.0.0.jar:?]
	at org.apache.directory.server.core.DefaultOperationManager.search(DefaultOperationManager.java:1345) [myvd-server-1.0.0.jar:2.0.0-M20]
	at org.apache.directory.server.core.shared.DefaultCoreSession.search(DefaultCoreSession.java:1113) [myvd-server-1.0.0.jar:2.0.0-M20]
	at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.doSimpleSearch(SearchRequestHandler.java:827) [myvd-server-1.0.0.jar:?]
	at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.handleIgnoringReferrals(SearchRequestHandler.java:1179) [myvd-server-1.0.0.jar:?]
	at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.handle(SearchRequestHandler.java:212) [myvd-server-1.0.0.jar:?]
	at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.handle(SearchRequestHandler.java:93) [myvd-server-1.0.0.jar:?]
	at org.apache.directory.server.ldap.handlers.LdapRequestHandler.handleMessage(LdapRequestHandler.java:207) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.directory.server.ldap.handlers.LdapRequestHandler.handleMessage(LdapRequestHandler.java:56) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:221) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.directory.server.ldap.LdapProtocolHandler.messageReceived(LdapProtocolHandler.java:217) [apacheds-service-2.0.0-M20.jar:?]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.runTask(UnorderedThreadPoolExecutor.java:475) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.run(UnorderedThreadPoolExecutor.java:429) [apacheds-service-2.0.0-M20.jar:2.0.0-M20]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

Whats erroring out is the ```CN=w99sb700 ,OU=UsersFunctional,OU=_Central,OU=AccSvc,OU=RA005,_DC=ad001,DC=siemens,DC=net``` is an invalid DN (I think its the _DC=ad001) thats the problem.

**Comment by mlbiam** [comment]
@ShivankSiemens I think I know what the problem is.  I think the bind DN for ad001 has the "_DC=" in it (its erroring out trying to connect).  Check there and change "_DC=" to "DC=".

**Comment by ShivankSiemens** [comment]
@mlbiam 
Thanks a lot Marc !
Finally I am able to login with user from both domains.

I have to conduct some tests on various user names and then I can confirm to you.

Meanwhile, I found that myVD proxy is not returning the login name (sAMaccountname) of users.
Because of which no new user can be added.

I have attached two screenshots. One when doing a search for a user with myVD and another our normal search when directly accessing LDAP.

Can you pls. have a look and let me know if we can get samaccountname as well in search result.

Thanks,
Shivank
![myvd import](https://cloud.githubusercontent.com/assets/23254772/20436838/edabe6c4-adb1-11e6-8942-35e23ff0bcc8.JPG)
![without myvd import](https://cloud.githubusercontent.com/assets/23254772/20436837/edaaf3fe-adb1-11e6-9cee-1a0a3aef5437.JPG)

**Comment by mlbiam** [comment]
@ShivankSiemens Instead of samccountname, use uid.  So your search would be for uid=z003n90u.

**Comment by ShivankSiemens** [comment]
@mlbiam 
Hi Marc,

I tried using the uid option as well. But, I am not getting the username which is essential for adding the login of any user in the system. Can we try to get LDAP username as well from MyVD as it is returned in the normal search ?

Please advise.

Thanks,
Shivank


![ldapsearch_uid](https://cloud.githubusercontent.com/assets/23254772/20474746/705f1c2c-afc8-11e6-8530-17a3af7de814.JPG)

**Comment by ShivankSiemens** [comment]
@mlbiam 
Hi Marc,

We were able to resolve the problem of user name earlier in the day. From your suggestion, we changed filed map in Primavera configuration file. (samaccountname to uid) It worked.

Thanks a lot for your prompt response and help.

In our testing, I found that: mvVD is working fine when defined in Primavera configuration but not when using Weblogic Server (Our Application Server).

I have defined AD001, Siemens.net and MyVD in 'Providers' settings in Weblogic (Security Realms) with MyVD given first priority.

Still, I am able to login for users in old domain only. Not the ad001 or migrated users.

Can you please advise further.

I am attaching the logs again. Let me know if you need screenshots of myVD config in weblogic as well.

[myvd.log (3).txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/603786/myvd.log.3.txt)

Thanks,
Shivank

**Comment by mlbiam** [comment]
@ShivankSiemens the issue is probably in weblogic, which can be really finicky around multiple directories.  A few things I would do:

1. Make sure MyVD is the only ldap directory configured (except for your local directory for weblogic admins if you're using it).
2. make sure MyVD is marked as sufficient in weblogic

Whats the name of the user that not working?

**Comment by ShivankSiemens** [comment]
@mlbiam 
The user which is not able to login is: z003n90u

It was present earlier in siemens.net but was migrated to ad001 and deactivated in the old domain.

When we mention multiple providers, we use the 'optional' seting. I will check for the sufficient setting in weblogic and update you.

**Comment by mlbiam** [comment]
@ShivankSiemens I think sufficient is what you want.  Also, make sure that MyVD is the only LDAP provider (remove individual configurations for AD001 and Siemens.net from weblogic)

**Comment by ShivankSiemens** [comment]
Hi @mlbiam 

I changed the setting to sufficient and restrated services -> Did not work
Then removed other ad001 and siemens.net configurations as well. Now only with -> Does not work

Now, it seems no other account is able to login as well. Earlier my username was able to login as I am still in old domain. Now no one is able to login.

Pls. advise further.

Thanks,
Shivank

**Comment by mlbiam** [comment]
@ShivankSiemens can you attach the logs?  Also if you want to do another screen share session i'm happy to do so.

**Comment by ShivankSiemens** [comment]
[myvd-weblogic.log.txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/605675/myvd-weblogic.log.txt)

@mlbiam 
Hi Marc,

I forgot to attach the logs yesterday. PFA now.

Yes, We can have a Live Meeting today again. I can schedule it anytime between 2:00 PM to 5:00 PM CET as per your convenience.
Just let me know here - at what time you can join. I will send the invite then.

Thanks,
Shivank

**Comment by ShivankSiemens** [comment]
@mlbiam 
Hi Marc, Can we have a meeting now ?

**Comment by mlbiam** [comment]
@ShivankSiemens sure, send me connection info direct to my email account

**Comment by mlbiam** [comment]
@ShivankSiemens can i close this issue?

**Comment by mlbiam** [comment]
@ShivankSiemens since we were able to get your setup running, I'm going to close this out.  IF you need further assistance, please open a new ticket.

**Comment by ShivankSiemens** [comment]
Thanks Marc for all your help ☺

Regards,
Shivank
