### ISSUE TITLE
Sizelimit Exceeded Exception

### ISSUE THREAD

**Issue by wbaeck** [TremoloSecurity/MyVirtualDirectory#71]
Hi

We get an exception every 20 seconds and wondering if there is a setting to increase the "Sizelimit"

```
[2019-09-05 22:29:17,944][EmbeddedGroups-embed-Sync][net.sourceforge.myvd.inserts.ldap.EmbeddedGroups] ERROR EmbeddedGroups - Error Synchronizing Groups
com.novell.ldap.LDAPException: Sizelimit Exceeded
        at com.novell.ldap.LDAPResponse.getResultException(LDAPResponse.java:407) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPResponse.chkResultCode(LDAPResponse.java:370) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPSearchResults.next(LDAPSearchResults.java:289) ~[jldap-1.0.0.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPEntrySet.getNextLDAPEntry(LDAPEntrySet.java:91) ~[myvd-server-1.0.6.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPEntrySet.getNextLDAPEntry(LDAPEntrySet.java:100) ~[myvd-server-1.0.6.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPEntrySet.getNextLDAPEntry(LDAPEntrySet.java:100) ~[myvd-server-1.0.6.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPEntrySet.getNextLDAPEntry(LDAPEntrySet.java:100) ~[myvd-server-1.0.6.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPEntrySet.hasMore(LDAPEntrySet.java:75) ~[myvd-server-1.0.6.jar:?]
        at net.sourceforge.myvd.types.Results.hasMore(Results.java:118) ~[myvd-server-1.0.6.jar:?]
        at net.sourceforge.myvd.inserts.ldap.EmbeddedGroups.staticLoadGroups(EmbeddedGroups.java:615) ~[myvd-server-1.0.6.jar:?]
        at net.sourceforge.myvd.inserts.ldap.RebuildGroups.run(EmbeddedGroups.java:729) [myvd-server-1.0.6.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

It only happens when there are more than 1000 local groups in my Active Directory.

I'm also wondering if there is a setting that my Active Directory isn't polled every 20 seconds for all the local groups?

Thank you very much in advance

**Comment by wbaeck** [comment]
We also changed ```MaxPageSize``` in Active Directory to 30000 without any success. 

(see http://it-toolkit.blogspot.com/2015/11/how-to-set-maxpagesize-in-active.html)

Any other ideas?

**Comment by wbaeck** [comment]
Could you please fix this? Please......
